version: 1.0.{build}

environment:
  matrix:
    - echo: echo
    #- echo: echo:second

build: off

before_deploy:
  - appveyor PushArtifact appveyor.yml -DeploymentName myArtifact
  
deploy:
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: YYaba3dPUneRem8KQzFCQCq7EmhJr9P8egf6Bp6OChFwdCkyQXDsL/ImEPe4rKHN
  artifact: myArtifact


test_script:
  - npm run %echo%
