version: 1.0.{build}

image: 
  #- Visual studio 2013
  #- Visual studio 2015
  - Visual studio 2017
platform:
  #- x86
  - anyCPU

#environment:
 # matrix:
  #  - echo: echo
    #- echo: echo:second
    
skip_branch_with_pr: true
build: off
install:
  - appveyor-retry powershell Start-FileDownload https://github.com/OwenMcDonnell/my-react-app/archive/testing.tar.gz -FileName testing.zip
  - dir
  - echo %platform%
  - echo %processor_architecture%
  - cmd: if %processor_architecture% == AMD64 (wmic OS get OSArchitecture)
  - echo %APPVEYOR_BUILD_NUMBER% > archive/test-file.txt
      
  #- appveyor PushArtifact appveyor.yml README.md -DeploymentName myArtifact
  #- appveyor PushArtifact README.md -DeploymentName myArtifact
build_script:
  #- mkdir archive
  - 7z a archive.zip appveyor.yml deploy.ps1
artifacts:
  - path: ./testing.zip
    name: archive
#build_script:
 # - appveyor PushArtifact appveyor.yml -DeploymentName myArtifact
  
#deploy:
 # release: testing
  #description: 'Release description'
  #provider: GitHub
  #auth_token:
   # secure: YYaba3dPUneRem8KQzFCQCq7EmhJr9P8egf6Bp6OChFwdCkyQXDsL/ImEPe4rKHN
  #artifact: myArtifact
  #force_update: true
  #on:
   # APPVEYOR_REPO_TAG: true
#deploy:
 # provider: Environment
  #name: ProjectA
  #auth_token:
   # secure: YYaba3dPUneRem8KQzFCQCq7EmhJr9P8egf6Bp6OChFwdCkyQXDsL/ImEPe4rKHN
  #artifact: myArtifact
  #force_update: true
  #on:
   # APPVEYOR_REPO_TAG: true
