version: 1.0.{build}

image: 
  #- Visual studio 2013
  - Visual studio 2015
  - Visual studio 2017
platform:
  - x86
  - anyCPU

#environment:
 # matrix:
  #  - echo: echo
    #- echo: echo:second
skip_branch_with_pr: true
build: off
install:

  - echo %platform%
  - echo %processor_architecture%
  - cmd: if %processor_architecture% == AMD64 (wmic OS get OSArchitecture)

      
  - appveyor PushArtifact appveyor.yml -DeploymentName myArtifact
#build_script:
 # - appveyor PushArtifact appveyor.yml -DeploymentName myArtifact
  
#deploy:
 # release: testing
  #description: 'Release description'
  #provider: GitHub
  #auth_token:
   # secure: YYaba3dPUneRem8KQzFCQCq7EmhJr9P8egf6Bp6OChFwdCkyQXDsL/ImEPe4rKHN
  #artifact: myArtifact
  #force_update: true
  #on:
   # APPVEYOR_REPO_TAG: true

