version: 1.0.{build}

image: 
  - Visual studio 2013
  - Visual studio 2015
  - Visual studio 2017

#environment:
 # matrix:
  #  - echo: echo
    #- echo: echo:second

build: off
install:
  #- cd ../..
  - echo %processor_architecture%
  - cmd: >-
  
      if %processor_architecture% == 'AMD64' (
        wmic OS get OSArchitecture
      ) else (
        echo "nope"
      )
      
  - appveyor PushArtifact appveyor.yml -DeploymentName myArtifact
#build_script:
 # - appveyor PushArtifact appveyor.yml -DeploymentName myArtifact
  
#deploy:
 # release: testing
  #description: 'Release description'
  #provider: GitHub
  #auth_token:
   # secure: YYaba3dPUneRem8KQzFCQCq7EmhJr9P8egf6Bp6OChFwdCkyQXDsL/ImEPe4rKHN
  #artifact: myArtifact
  #force_update: true
  #on:
   # APPVEYOR_REPO_TAG: true

test_script:
  #- npm run %echo%
