version: 1.0.{build}

environment:
  matrix:
    - echo: echo
    #- echo: echo:second

#build: off
build_script:
  - appveyor PushArtifact appveyor.yml -DeploymentName myArtifact
  
deploy:
  release: testing
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: YYaba3dPUneRem8KQzFCQCq7EmhJr9P8egf6Bp6OChFwdCkyQXDsL/ImEPe4rKHN
  artifact: myArtifact
  force_update: true



test_script:
  - npm run %echo%
