version: 1.0.{build}

environment:
  matrix:
    - echo: echo
    #- echo: echo:second
  
build_script:
  - appveyor PushArtifact appveyor.yml -DeploymentName myArtifact


test_script:
  - npm run %echo%
