version: 1.0.{build}

#image: Ubuntu

environment:
  matrix:
    - echo: echo
    #- echo: echo:second

build: off
before_deploy:
  - cd ../..
  - 7z a -ir **\*_parsed*.xml -bd expected_parsed.zip
  - appveyor PushArtifact appveyor.yml -DeploymentName myArtifact
#build_script:
 # - appveyor PushArtifact appveyor.yml -DeploymentName myArtifact
  
deploy:
  release: testing
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: YYaba3dPUneRem8KQzFCQCq7EmhJr9P8egf6Bp6OChFwdCkyQXDsL/ImEPe4rKHN
  artifact: myArtifact
  #force_update: true
  #on:
   # APPVEYOR_REPO_TAG: true

test_script:
  #- npm run %echo%
